### PR TITLE
General Code Hygiene

### PR DESCRIPTION
**Pull request by TheKingOfShade**
Added two functions that help to reduce redundancy, and made some flow-of-control modifications. Added a few comments to make it a bit easier to read. No functional changes. Be gentle with me, as I don't have the ability to check for bugs, and it is, in fact, my first time.

### CODE REVIEW

**Comment by secgroundzero** [comment]
thank you. i need some time to go through your code and verify the changes work ok

**Comment by E3V3A** [comment]
@secgroundzero Did you finish checking?

**Comment by secgroundzero** [comment]
no because i am in the process of making changes that will affect this code as well.

i have another demo version and importing code slowly

**Comment by secgroundzero** [comment]
will revisit this as the code is updated

**Pull request closed without merging**
