### PR TITLE
Mail Credential getter

### PR DESCRIPTION
**Pull request by thecarterb**
# Summary

Added a small script in `warberry.py` to get plaintext email usernames and passwords when run in malicious mode.
The script is located [on my GitHub here](https://github.com/thecarterb/mail0wner)
Also added a `git clone` command to `boolstrap.sh` to clone the repo.

### CODE REVIEW

**Comment by secgroundzero** [comment]
hi man and thanks but your github repo cannot be found.

was it deleted?

**Comment by thecarterb** [comment]
That's odd. I'll take a look at it and see what's up

**Comment by thecarterb** [comment]
Should be all good now. I accidentally marked the repo as private when I created it.

**Comment by thecarterb** [comment]
Awesome, thanks! Let me know if you want any additional things included in the script.

**Comment by secgroundzero** [comment]
ok i am testing and it looks fine. just a comment. i want to add a timeout in case a packet is not obtained after a certain period of time so that the script does not hang there.

**Comment by thecarterb** [comment]
okay, i'll try to work on it today, if not tomorrow.

**Comment by secgroundzero** [comment]
the timeout can be set with timeout=<time> in scapy

i would rather implement this script directly in the mail script instead of calling it from an external file.

**Comment by thecarterb** [comment]
okay, ill get on it

**Comment by thecarterb** [comment]
should be good now

**Comment by secgroundzero** [comment]
thank you. implemented in a slightly different way.

Credits have been given to you in the Changelog!

**Comment by secgroundzero** [comment]
there is a problem when the interface in used is wlan0 and not eth.

pls check the error

**Comment by thecarterb** [comment]
will do

**Pull request closed without merging**
