### PR TITLE
Fixed a number of issues.

### PR DESCRIPTION
**Pull request by robinlennox**
If WarBerry is cloned to a folder other that a user called Pi, the script will still run. Also added a ignore file so the python byte code is not added to git.

### CODE REVIEW

**Comment by secgroundzero** [comment]
it seems that the ipv4 checking is not correct as any address is accepted.

**Comment by secgroundzero** [comment]
most of your changes have been implemented and they will be rolled out soon after complete testing is done. thank you

**Comment by robinlennox** [comment]
Thanks good to hear about my change!

I can't replicate the IPv4 issue which you are having... could you provide me an IP where you think it should be marked as public and fail? As I can't replicate the issue.

**Comment by secgroundzero** [comment]
That module checks if the ip is a valid private one not public.

Your code was verifying its public

**Comment by robinlennox** [comment]
Nope it checking that it's private... try setting int_ip='8.8.8.8' then print within the if statement it won't print, then set int_ip to '172.16.1.1' it will then print.

**Comment by secgroundzero** [comment]
I tried in a network which sets static ips and i did not get one so i had 196.169...  Still thought it was a valid internal ip

**Comment by robinlennox** [comment]
Valid Private IPv4 ranges are:

192.168.0.0/16
172.16.0.0/12
10.0.0.0/8

Here's a link to them: https://en.wikipedia.org/wiki/Private_network. 196.169.x.x is a public IP. My method also works for IPv6 :)

**Comment by secgroundzero** [comment]
Exactly why it should work.  I want to validate the internal ip not the external :)

**Comment by robinlennox** [comment]
It does that. If the IP is private the function ip_validate returns FALSE

The if statement - if not ip_validate(int_ip):

Works as follows

If value returned from ip_validate is not TRUE (Public IP) then run code...  else exit.

Have you tried the code? It does work... I've tried it multiple times now and works everytime...

**Comment by robinlennox** [comment]
Try this:

def ip_validate(ip_addr): #Check if IP is public
    ip_addr = IPAddress(ip_addr)
    return ip_addr.is_private() and not ip_addr.is_loopback() and not ip_addr.is_reserved() and not ip_addr.is_hostmask()

**Comment by secgroundzero** [comment]
I will try again

**Pull request closed without merging**
