### PR TITLE
add more local ip's to discover

### PR DESCRIPTION
**Pull request by thecarterb**
added 172.16.0.0/24 and 172.31.255.0/24 to `discover`

### CODE REVIEW

**Comment by secgroundzero** [comment]
thank you. pls note that these IPs are used only for demo purposes. in real life any ip should work

**Comment by ikirt** [comment]
Nice you beat me to it :)
Wrote up a similar email_cred_sniffer

**Comment by secgroundzero** [comment]
thank you both for your contributions

**Comment by ikirt** [comment]
more to come :)

**Pull request closed without merging**
