### PR TITLE
Update bootstrap.sh and add interface check for mailowner

### PR DESCRIPTION
**Pull request by thecarterb**

### CODE REVIEW

**Comment by secgroundzero** [comment]
implemented without duplicated code.

sniff(filter="tcp port 110 or tcp port 25 or tcp port 143", iface=iface, prn=packet_callback, store=0, timeout=expire)

sending the iface from the options.iface param

will update now

**Comment by secgroundzero** [comment]
please test the mailowner module too.

one out of 3 times it throws an error i cant spot

**Comment by thecarterb** [comment]
okay i'll check it out. can you send me the error code?

**Comment by thecarterb** [comment]
I've tested it a few times and never got an error message with the mail owner module, but i did with the pcap parser module.

**Comment by secgroundzero** [comment]
You are missing the net creds tool.

You can check the dependencies for which repo you need

**Comment by thecarterb** [comment]
fixed the locations of all of the tools, still no error in the mailowner module

**Pull request closed without merging**
